{
 "title": "Host",
 "description": "Shows Statistics Collected from XVMS on a given host.",
 "tags": [ "rumi" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "influxdb" },
   {
    "name": "host_name",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"rumi_heartbeat_rp\".\"application\" WITH KEY = \"host_name\""
   },
   {
    "name": "system_name",
    "label": "System",
    "query": "SHOW TAG VALUES FROM \"rumi_heartbeat_rp\".\"application\" WITH KEY = \"system_name\" WHERE \"host_name\" =~ /^$host_name$/"
   },
   {
    "name": "vm_name",
    "label": "XVM",
    "query": "SHOW TAG VALUES FROM \"rumi_heartbeat_rp\".\"system\" WITH KEY = \"vm_name\" WHERE host_name =~ /^$host_name$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "XVMs",
   "type": "table",
   "description": "This table summarizes high-level resource usage for each XVM that reported stats during the selected time interval. \n\nClicking on a row will take you to the XVM dashboard for the XVM. \n\n* **Last Heartbeat**: The time of last collected heartbeat for the XVM. \n* **XVM**: The name of the XVM.\n* **Loaded Time**: The time at which the XVM was loaded.\n* **CPU**: The last reported value of recent CPU usage by the XVM's process. \n* **Heap Used**: The amount of used heap memory currently in use. \n* **Heap Committed**: The amount of heap memory guaranteed (committed) for the Java virtual machine to use.\n* **Heap Max**: The maximum heap memory size in bytes.\n* **Off Heap**: The amount of used off-heap memory in bytes.\n\n*XVMs that have since been terminated will be listed here until none of their collected heartbeats fall within the selected time interval.*",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"xvm_loaded_time\") as \"Loaded Time\", \"process_cpu_load\" as \"CPU\", \"memory_heap_used\" as \"Heap Used\", \"memory_heap_committed\" as \"Heap Committed\", \"memory_heap_max\" as \"Heap Max\", \"memory_non_heap_used\" as \"Off Heap\" FROM \"rumi_heartbeat_rp\".\"system\" WHERE \"host_name\" =~ /^$host_name$/ AND \"system_name\" =~ /^$system_name$/ AND $timeFilter GROUP BY \"vm_name\" ORDER BY time ASC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk (Free)",
   "type": "timeseries",
   "description": "This table lists the amount of free disk space available on each volume discovered by XVMs running on the target host. \n\nThe values shown are current to the last reported heartbeat collected by an XVM running on the host. If no heartbeats have been reported by any XVM in the selected time interval, then no data will be shown.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_disk_root",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "disk_root" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system.disk",
     "select": [
      [
       { "params": [ "disk_usable_space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Usable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "This graph shows total available memory and used memory as reported by the last heartbeat received from an XVM running on the host. \n\nThe values shown are current to the last reported heartbeat collected by an XVM running on the host. If no heartbeats have been reported by any XVM in the selected time interval, then no data will be shown.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"memory_physical_size_total\") - last(\"memory_physical_size_free\")) AS \"Free\" FROM \"rumi_heartbeat_rp\".\"system\" WHERE \"host_name\" =~ /^$host_name$/ AND \"memory_physical_size_total\" > 0 AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"memory_physical_size_total\") AS \"Used\" FROM \"rumi_heartbeat_rp\".\"system\" WHERE \"host_name\" =~ /^$host_name$/ AND \"memory_physical_size_total\" > 0 AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_physical_size_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_physical_size_free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU (Host)",
   "type": "timeseries",
   "description": "This graph shows total cpu usage as reported by the last heartbeat received from an XVM running on the host. \n\nThe values shown are current to the last reported heartbeat collected by an XVM running on the host. If no heartbeats have been reported by any XVM in the selected time interval, then no data will be shown.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"system_cpu_load\") AS \"Total\" FROM \"rumi_heartbeat_rp\".\"system\" WHERE \"host_name\" =~ /^$host_name$/ AND \"system_cpu_load\" > 0 AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_physical_size_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_physical_size_free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU (Thread)",
   "type": "timeseries",
   "description": "This panel shows the last reported CPU usage by any thread for which stats were collected in the selected time range.\n\n* **XVM**: ﻿The XVM that owns the thread. \n* **ID**: ﻿The Thread ID.\n* **Thread Name**: ﻿The name of the thread. \n* **Affinity**: ﻿When threads are pinned to one or more cores, the affinity information is displayed here. \n* **CPU**: ﻿The percentage of CPU time per interval used by the thread. Note that this can be thought of as the number of cycles used on a logical core of the host. \n* **USER**: ﻿The percentage of the processing time that was in user mode (vs kernel). \n* **﻿WAIT**: ﻿The percentage of time that the thread spent waiting in a disruptor. This is particularly useful if the thread is configured with a disruptor wait strategy of busy spin or yielding as it can tell what portion of used CPU time the thread spent spinning. \n\n*If a thread has since stopped, it's last reported CPU will continue to be displayed until it's activity is no longer reflected in the selected time window.*",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system.threads",
     "query": "SELECT \"id\" as \"ID\", last(\"name\") AS \"Thread Name\", \"affinity\" FROM \"rumi_heartbeat_rp\".\"system.threads\" WHERE \"host_name\" =~ /^$host_name$/ AND \"system_name\" =~ /^$system_name$/ AND $timeFilter GROUP BY \"vm_name\",\"id\" ORDER BY time ASC LIMIT 1",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host_name$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system.threads",
     "query": "SELECT difference(\"cpu_time\") / difference(\"collect_time\") AS \"cpu_pct\" FROM \"rumi_heartbeat_rp\".\"system.threads\" WHERE \"host_name\" =~ /^$host_name$/ AND  \"system_name\" =~ /^$system_name$/ AND $timeFilter GROUP BY \"vm_name\",\"id\"  ORDER BY time ASC LIMIT 1",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host_name$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system.threads",
     "query": "SELECT difference(\"usr_time\") / difference(\"collect_time\")  AS \"usr_pct\" FROM \"rumi_heartbeat_rp\".\"system.threads\"  WHERE \"host_name\" =~ /^$host_name$/ AND  \"system_name\" =~ /^$system_name$/ AND $timeFilter GROUP BY \"vm_name\",\"id\" ORDER BY time ASC LIMIT 1",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host_name$/" }
     ]
    },
    {
     "alias": "WAIT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system.threads",
     "query": "SELECT difference(\"wait_time\") / difference(\"collect_time\") AS \"wait_pct\" FROM \"rumi_heartbeat_rp\".\"system.threads\" WHERE \"host_name\" =~ /^$host_name$/ AND  \"system_name\" =~ /^$system_name$/ AND $timeFilter GROUP BY \"vm_name\",\"id\" ORDER BY time ASC LIMIT 1",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host_name", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  }
 ]
}