{
 "title": "VM",
 "description": "The XVM Stats dashboard provides monitoring information about the resources used by and applications running within a given XVM.",
 "tags": [ "rumi" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "influxdb" },
   {
    "name": "system_name",
    "label": "System",
    "query": "SHOW TAG VALUES FROM \"rumi_heartbeat_rp\".\"application\" WITH KEY = \"system_name\""
   },
   {
    "name": "vm_name",
    "label": "XVM",
    "query": "SHOW TAG VALUES FROM \"rumi_heartbeat_rp\".\"application\" WITH KEY = \"vm_name\" WHERE \"system_name\" =~ /^$system_name$/"
   },
   {
    "name": "app_name",
    "label": "Application",
    "query": "SHOW TAG VALUES FROM \"rumi_heartbeat_rp\".\"application\" WITH KEY = \"app_name\" WHERE vm_name =~ /^$vm_name$/ AND \"system_name\" =~ /^$system_name$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "description": "Lists summary details about the state of applications included in XVM heartbeats during the selected time interval. \n\nApplications that have since been unloaded will be listed here until there are no heartbeats that include their state reported in the selected time interval. \n\n* **Last Heartbeat**: The time of the last heartbeat received from the XVM. \n* **Application**: The name of the application\n* **State**: The state of the application as last reported in a heartbeat.\n* **Role**: The last reported HA role for the application \n* **HA Policy**: The application's HA Policy\n* **Loaded Time**: The time at which the application was loaded.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application",
     "query": "SELECT last(\"state\") AS \"State\", \"role\" as \"Role\", \"ha_policy\" as \"HA Policy\", \"loaded_time\" as \"Loaded Time\" FROM \"rumi_heartbeat_rp\".\"application\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY \"app_name\", \"vm_name\"",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Since",
   "type": "stat",
   "description": "The last reported CPU Usage for the Host (including other processes) as reported in the last collected XVM heartbeat.",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "xvm_loaded_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Process CPU Load",
   "type": "stat",
   "description": "The last reported CPU Usage for the application's process (including other apps in the XVM) as reported in the last collected XVM heartbeat.",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "process_cpu_load" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Host CPU Load",
   "type": "stat",
   "description": "The last reported CPU Usage for the application's process (including other apps in the XVM) as reported in the last collected XVM heartbeat.",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "system_cpu_load" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Host Memory Used",
   "type": "stat",
   "description": "The number of CPUs as reported in the last collected XVM heartbeat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT ((last(\"memory_physical_size_total\") - last(\"memory_physical_size_free\"))/last(\"memory_physical_size_total\")) AS \"Memory Used\" FROM \"rumi_heartbeat_rp\".\"system\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "processors" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Host Cpus",
   "type": "stat",
   "description": "The number of CPUs as reported in the last collected XVM heartbeat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT last(\"threads_count\") FROM \"rumi_heartbeat_rp\".\"system\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "processors" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Process Threads",
   "type": "stat",
   "description": "The number of thread as reported in the last collected XVM heartbeat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"threads_count\") FROM \"rumi_heartbeat_rp\".\"system\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "threads_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "description": "Shows garbage collection duration grouped by the collector type. \n\nThe graph renders the delta of the total time spent collecting by each collector as reported in successive intervals ... if more than one collection occurs within a heartbeat collection interval their combined collection time will be shown.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_collector_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "collector_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system.gc",
     "query": "SELECT difference(\"cum_time\") FROM \"rumi_heartbeat_rp\".\"system.gc\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY \"collector_name\" fill(none)",
     "select": [
      [
       { "params": [ "cum_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Just In Time Compiler",
   "type": "timeseries",
   "description": "Shows jit compilation times grouped by the compiler type. \n\nThe graph renders the delta of the total time spent compiling by each compiler as reported in successive intervals ... if more than one compilation occurs within a heartbeat collection interval their combined compilation times will be shown.\n\nJIT compilation is not necessarily a stop the world operation, but may still contribute to jitter.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_jit_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "jit_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT difference(\"cum_time\") FROM \"rumi_heartbeat_rp\".\"system.gc\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY \"collector_name\" fill(none)",
     "select": [
      [
       { "params": [ "jit_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "This graph shows the heap memory usage for the process as reported by the last heartbeat received from the XVM.\n\n* **Heap Used**: The amount of heap memory currently used by the application. \n* **Heap Init**: The amount of heap memory that the Java virtual machine initially requested from the operating system.\n* **Heap Committed**: The amount of heap memory guaranteed (committed) for the Java virtual machine to use.\n* **Heap Max**: The maximum amount of memory in bytes that can be used for heap memory management.\n\n  This amount of memory is not guaranteed to be available for memory management if it is greater than the amount of committed memory. The Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.\n\n  A value of -1 indicates that the maximum memory size is undefined.\n\n*The values shown are current to the last reported heartbeat collected by this XVM. If no heartbeats have been reported in the selected time interval, then no data will be shown.*",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT \"memory_heap_used\" as \"Heap Used\",  \"memory_heap_init\" as \"Heap Init\", \"memory_heap_committed\" as \"Heap Committed\",  \"memory_heap_max\" as \"Heap Max\"  FROM \"rumi_heartbeat_rp\".\"system\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "memory_heap_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Non Heap Memory Usage",
   "type": "timeseries",
   "description": "This graph shows the non-heap memory usage for the process as reported by the last heartbeat received from this XVM.\n\n* **Non-Heap Used**: The amount of non-heap memory used by the process in which the application is running. \n* **Non-Heap Init**: The amount of non-heap memory that the Java virtual machine initially requests from the operating system.\n* **Non-Heap Committed**: This amount of non-heap memory guaranteed (committed) for the Java virtual machine to use.\n* **Non-Heap Max**: The maximum amount memory in bytes that can be used for non-heap memory management.\n\n  This amount of memory is not guaranteed to be available for memory management if it is greater than the amount of committed memory. The Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.\n\n  A value of -1 indicates that the maximum memory size is undefined.\n\n*The values shown are current to the last reported heartbeat collected by this XVM. If no heartbeats have been reported in the selected time interval, then no data will be shown.*",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT  \"memory_non_heap_used\" as \"Non Heap Used\",  \"memory_non_heap_init\" as \"Non Heap Init\", \"memory_non_heap_committed\" as \"Non Heap Committed\",  \"memory_non_heap_max\" as \"Non Heap Max\"  FROM \"rumi_heartbeat_rp\".\"system\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "memory_heap_committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Off Heap Memory Usage",
   "type": "timeseries",
   "description": "This graph shows the off-heap memory usage for the process as reported by the last heartbeat received from this XVM.\n\n* **Bytes Live (Native)**: The amount of live off-heap memory that the process has directly allocated as native memory blocks. \n* **Bytes Live (IOBuf)**: The amount of live off-heap memory that the process is using via allocated IO Buffers. \n* **Bytes Pooled**: This amount of off-heap memory pooled/cached for future use.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT  \"memory_iobuf_bytes_pooled\" as \"Bytes Pooled\", \"memory_native_bytes_live\" as \"Bytes Live (Native)\", \"memory_iobuf_bytes_live\" as \"Bytes Live (IOBuf)\" FROM \"rumi_heartbeat_rp\".\"system\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "memory_heap_committed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "timeseries",
   "description": "This graph shows overall memory usage for the host on which this XVM is running as reported by the last heartbeat received from this XVM. \n\n* **Host Used**: The total amount of physical memory currently in use on the host. \n* **Host Total**: The total amount of physical memory on the host. \n\n*The values shown are current to the last reported heartbeat collected by this XVM. If no heartbeats have been reported in the selected time interval, then no data will be shown.*",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT (last(\"memory_physical_size_total\") - last(\"memory_physical_size_free\")) AS \"Host Used\" FROM \"rumi_heartbeat_rp\".\"system\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_physical_size_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"memory_physical_size_total\") AS \"Host Total\" FROM \"rumi_heartbeat_rp\".\"system\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_physical_size_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Heartbeat Emission",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Binary Heartbeat Logger",
     "type": "timeseries",
     "description": "When Binary heartbeat logging is enabled for the XVM, this graph charts this size of the file.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "File Size",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "xvm.heartbeats.logger",
       "query": "SELECT last(\"file_size\") AS \"File Size\" FROM \"rumi_heartbeat_rp\".\"application.pertransactionstats.logger\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "file_size" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "File Size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
       ]
      },
      {
       "alias": "File Size Used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "xvm.heartbeats.logger",
       "query": "SELECT last(\"file_size\") AS \"File Size\" FROM \"rumi_heartbeat_rp\".\"application.pertransactionstats.logger\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "file_size_used" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "File Size Used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
       ]
      }
     ]
    },
    {
     "title": "Binary Heartbeat Logger Stats",
     "type": "table",
     "description": "When binary heartbeat logging is enabled for the XVM, this table displays binary heartbeat logging statistics from the last heartbeat received from the XVM. \n\n* **Commits**: The number of times the logger has been committed.\n* **Heartbeats Logged**: The number of heartbeats logged to the file. \n* **File Size**: The size of the file in on disk. \n* **File Size Used**: The size of the file that is used (which may be less than File Size if the file was preallocated). \n*  **Average Entry Size**: The average size of entries logged.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"commits\") AS \"Commits\", \"messages\" AS \"Messages\", \"file_size\" AS \"File Size\", \"file_size_used\" AS \"File Size Used\" FROM \"rumi_heartbeat_rp\".\"xvm.heartbeats.logger\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter ORDER BY time DESC LIMIT 1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT (last(\"file_size_used\") / last(\"messages\")) AS \"Average Entry Size\"  FROM \"rumi_heartbeat_rp\".\"xvm.heartbeats.logger\" WHERE \"vm_name\" =~ /^$vm_name$/ AND \"messages\" > 0 AND $timeFilter ORDER BY time DESC LIMIT 1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Admin Client Stats",
     "type": "table",
     "description": "This panel reports heartbeat emission statistics for admin clients that have connected to the XVM during the selected time interval. \n\nThis table can be used to determine what data is being sent to each client and whether or not any data was dropped by the XVM due to client congestion. \n\n* **Q Capacity**: The size of the delivery queue for the admin client. \n* **Q Size**: The size of admin packets currently queued for delivery to the client. \n*  **Queued**: The number of admin packets currently queued for the client. \n* **Heartbeats Sent**: The cumulative number of heartbeats sent to the client:\n* **Heartbeats Dropped**: The number of heartbeats dropped for this client due to client congestion. \n* **Trace Records Sent**: The cumulative number of trace records sent to the client:\n* **Trace Records Dropped**: The number of trace records dropped for this client due to client congestion. \n* **Lifecycle Events Sent**: The cumulative number of lifecycle events sent to the client.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "client.admin",
       "query": "SELECT last(\"outboundQueueCapacity\") AS \"Q Capacity\", (\"outboundQueueSize\") AS \"Q Size\", \"outboundQueueCount\" AS \"Queued\" FROM \"rumi_heartbeat_rp\".\"client.admin\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY \"name\" fill(previous)",
       "select": [
        [
         { "params": [ "lifecyclesSent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Lifecycle Events Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "client.admin",
       "query": "SELECT last(\"heartbeatsSent\") - min(\"heartbeatsSent\") AS \"Heartbeats Sent\" FROM \"rumi_heartbeat_rp\".\"client.admin\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY \"name\" fill(previous)",
       "select": [
        [
         { "params": [ "lifecyclesSent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Lifecycle Events Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "client.admin",
       "query": "SELECT last(\"heartbeatsDropped\")  - min(\"heartbeatsDropped\") AS \"Heartbeats Dropped\" FROM \"rumi_heartbeat_rp\".\"client.admin\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY \"name\" fill(previous)",
       "select": [
        [
         { "params": [ "lifecyclesSent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Lifecycle Events Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "client.admin",
       "query": "SELECT last(\"tracesSent\") - min(\"tracesSent\") AS \"Trace Records Sent\" FROM \"rumi_heartbeat_rp\".\"client.admin\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY \"name\" fill(previous)",
       "select": [
        [
         { "params": [ "lifecyclesSent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Lifecycle Events Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "client.admin",
       "query": "SELECT last(\"tracesDropped\")  - min(\"tracesDropped\")  AS \"Trace Records Dropped\" FROM \"rumi_heartbeat_rp\".\"client.admin\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY \"name\" fill(previous)",
       "select": [
        [
         { "params": [ "lifecyclesSent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Lifecycle Events Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "client.admin",
       "query": "SELECT last(\"lifecyclesSent\")  - min(\"lifecyclesSent\") AS \"Events Sent\" FROM \"rumi_heartbeat_rp\".\"client.admin\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY \"name\" fill(previous)",
       "select": [
        [
         { "params": [ "lifecyclesSent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Lifecycle Events Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "client.admin",
       "query": "SELECT last(\"lifecycleDropped\")  - min(\"lifecycleDropped\") AS \"Events Dropped\" FROM \"rumi_heartbeat_rp\".\"client.admin\" WHERE \"vm_name\" =~ /^$vm_name$/ AND $timeFilter GROUP BY \"name\" fill(previous)",
       "select": [
        [
         { "params": [ "lifecyclesSent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Lifecycle Events Sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vm_name", "operator": "=~", "value": "/^$vm_name$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}